# Generated by Django 6.1 on 2026-08-27 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending_ai_analysis', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('urgency_score', models.IntegerField(default=50)),
                ('skills_required', models.JSONField(default=list)),
                ('estimated_cost', models.CharField(max_length=50)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_dna', to='api.challenge')),
            ],
        ),
    ]
